# Generated by Django 4.2 on 2024-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_flan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
        ),
    ]
