# Generated by Django 4.2 on 2024-05-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_flan_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
