# Generated by Django 4.2 on 2024-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
