# Generated by Django 4.2 on 2024-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_flan_alto_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='alto_calorias',
            field=models.BooleanField(default=False),
        ),
    ]
